# lightning.pytorch==2.4.0
seed_everything: true
lr: 0.0004
wdecay: 0.0001
trainer:
  max_epochs: 45
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
model:
  class_path: ptlflow.models.raft
  init_args:
    corr_levels: 4
    corr_radius: 4
    dropout: 0.0
    gamma: 0.8
    max_flow: 400.0
    iters: 12
    alternate_corr: false
    warm_start: false
data:
  train_dataset: chairs
  val_dataset: sintel-final-val+kitti-2015-val
  train_batch_size: 10
  train_num_workers: 4
  train_crop_size: [368, 496]
  train_transform_cuda: false
  train_transform_fp16: false
