# lightning.pytorch==2.4.0
seed_everything: true
ckpt_path: /path/to/sintel.ckpt  # Change to the ckpt resulting from rpknet-train3-sintel
lr: 0.000125
wdecay: 0.00001
trainer:
  max_epochs: 150
  check_val_every_n_epoch: 10
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  devices: 0,
model:
  class_path: ptlflow.models.rpknet
  init_args:
    pyramid_ranges:
    - 32
    - 8
    iters: 12
    input_pad_one_side: false
    input_bgr_to_rgb: false
    detach_flow: true
    corr_mode: allpairs
    upgate_norm_type: group
    use_norm_affine: false
    group_norm_num_groups: 4
    corr_levels: 1
    corr_range: 4
    enc_norm_type: group
    enc_stem_stride: 2
    enc_depth: 2
    enc_mlp_ratio: 4.0
    enc_hidden_chs:
    - 32
    - 64
    - 96
    enc_out_1x1_chs: '2.0'
    dec_gru_iters: 2
    dec_gru_depth: 2
    dec_gru_mlp_ratio: 4.0
    dec_net_chs: null
    dec_inp_chs: null
    dec_motion_chs: 128
    use_upsample_mask: true
    upmask_gradient_scale: 1.0
    cache_pkconv_weights: false
    gamma: 0.85
    max_flow: 400
    warm_start: false
data:
  train_dataset: kitti-2015
  val_dataset: kitti-2015-val+sintel-final-val
  train_batch_size: 6
  train_num_workers: 3
  train_crop_size: [288, 960]
  train_transform_cuda: false
  train_transform_fp16: false