# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lightning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lightning: ["2.1.4", "2.2.5", "2.3.3", "2.4.0", "2.5.1"]

    steps:
      - uses: actions/checkout@v4
      - name: Replace lightning
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "lightning[pytorch-extra]>=2,<2.5"
          replace: "lightning[pytorch-extra]==${{ matrix.lightning }}"
          regex: false
          include: "requirements.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest==8.3.3
          python -m pytest tests/
