# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytorch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pytorch: [
          'torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cpu',
          'torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu',
          'torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cpu',
          'torch==2.2.2 torchvision==0.17.2 --index-url https://download.pytorch.org/whl/cpu',
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.pytorch }}
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest==8.3.3
          python -m pytest tests/
